insta_app:
    resource: "@InstaAppBundle/Controller/"
    type:     annotation
    prefix:   /
    
login_check:
    path:   /login_check
 
logout:
    path:   /logout
    
#php app/console generate:controller --controller=InstaAppBundle:nomcontroller