security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
  
    encoders:
        'FOS\UserBundle\Model\UserInterface': sha512
  
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall pour les pages de connexion, inscription, et récupération de mot de passe
        login:
            pattern:   ^/(login$|resetting|register)
            anonymous: true                         
 
        # Firewall principal pour le reste de notre site
        main:
            pattern: ^/                             
            form_login:                             
                provider:    fos_userbundle         
                remember_me: true                   
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                #csrf_provider: form.csrf_provider
                default_target_path: /
            remember_me:
                key:         %secret%               
            anonymous:       false                  
            logout:          true                   
  
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
  
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
#    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
#    encoders:
#        Symfony\Component\Security\Core\User\User:
#            algorithm: bcrypt
#            cost: 12
#
#
#    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
#   # role_hierarchy:
#   #     ROLE_ADMIN:       [ROLE_USER]
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory:
#                users:
#                    ryan: { password: $2a$12$w/aHvnC/XNeDVrrl65b3dept8QcKqpADxUlbraVXXsC03Jam5hvoO, roles: [ 'ROLE_USER' ] }
#                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
# 
#
#    # the main part of the security, where you can set up firewalls
#    # for specific sections of your app
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#
#        
#        # secures part of the application
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
 #           form_login:
 #               login_path:  login
 #               check_path:  login_check
 #               use_referer: true
 #           logout:
 #               path: /logout
 #               target: /
#
 #   # with these settings you can restrict or allow access for different parts
 #   # of your application based on roles, ip, host or methods
 #   # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
 #   access_control:
 ##       - { path: ^/admin, roles: ROLE_ADMIN }