insta_app_homepage:
    path:     /
    defaults: { _controller: InstaAppBundle:Default:index }
    
insta_app_planning:
    path:       /planning
    defaults: { _controller: InstaAppBundle:Planning:index }

