insta_app_homepage:
    path:     /
    defaults: { _controller: InstaAppBundle:Default:index }
    
insta_app_planning:
    path:       /planning
    defaults: { _controller: InstaAppBundle:Planning:index }
    
insta_app_login:
    path:       /login
    defaults: { _controller: InstaAppBundle:Security:login }
    
login_check:
    path:   /login
    defaults: { _controller: InstaAppBundle:Security:loginCheck }
    
logout:
    path:   /logout


