insta_app_homepage:
    path:     /
    defaults: { _controller: InstaAppBundle:Default:index }
    
insta_app_connection:
    path:       /login
    defaults: { _controller: InstaAppBundle:Default:connection }
